import { WithContext, WebSite } from 'schema-dts';

const jsonLd: WithContext<WebSite> = {
  '@context': 'https://schema.org',
  '@type': 'WebSite',
  name: 'My Cosmetics',
  description: 'Generated by create next app',
};

export default function Home() {
  return (
    <main>
      <h1>Welcome</h1>

      {/* Add JSON-LD to your page */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
    </main>
  );
}
