import { Inter } from 'next/font/google';
import type { Metadata } from 'next';

import '~/styles/globals.css';

export const metadata: Metadata = {
  title: 'Admin',
  description: 'Generated by create next app',
};

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`relative ${inter.className}`}>{children}</body>
    </html>
  );
}
