import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Admin',
  description: 'Generated by create next app',
};

export default function Page() {
  return (
    <>
      <h1>Admin </h1>
    </>
  );
}
